//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiaire()
        {
            this.Coupons_Bnf = new HashSet<Coupons_Bnf>();
            this.Formation_Bnf = new HashSet<Formation_Bnf>();
            this.Inscriptions = new HashSet<Inscription>();
            this.Santes = new HashSet<Sante>();
        }
    
        public int Bnf_ID { get; set; }
        public string Bnf_Prenom { get; set; }
        public string Bnf_Nom { get; set; }
        public System.DateTime Bnf_DateNais { get; set; }
        public string Bnf_Sexe { get; set; }
        public string Bnf_NumAssMaladie { get; set; }
        public string Bnf_NumAssSocial { get; set; }
        public string Bnf_NumSecRev { get; set; }
        public System.DateTime Bnf_DateEnregistrementIns { get; set; }
        public Nullable<int> Scolar_ID { get; set; }
        public Nullable<int> Origine_ID { get; set; }
        public decimal Bnf_Total_Hebergement { get; set; }
        public decimal Bnf_Total_Coupon { get; set; }
    
        public virtual Origine Origine { get; set; }
        public virtual Scolar Scolar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupons_Bnf> Coupons_Bnf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formation_Bnf> Formation_Bnf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription> Inscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sante> Santes { get; set; }
    }
}
