//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons_Bnf
    {
        public int CouponsBnf_ID { get; set; }
        public int CouponsBnf_Qty { get; set; }
        public System.DateTime CouponsBnf_DateDemande { get; set; }
        public Nullable<int> Ins_ID { get; set; }
        public int Coupons_ID { get; set; }
        public int Bnf_ID { get; set; }
        public Nullable<decimal> Taxis_Prices { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual Coupons_Type Coupons_Type { get; set; }
    }
}
