//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours_Cond
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours_Cond()
        {
            this.Cours_Ins = new HashSet<Cours_Ins>();
        }
    
        public int Cours_Cond_ID { get; set; }
        public string CoursCond_AvocatName { get; set; }
        public string CoursCond_AvocatTel { get; set; }
        public string CoursCond_AgentProbName { get; set; }
        public string CoursCond_AgentProbTel { get; set; }
        public string CourCond_AgentProbPoste { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours_Ins> Cours_Ins { get; set; }
    }
}
