//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours_Ins
    {
        public int CoursCond_ID { get; set; }
        public int Ins_ID { get; set; }
        public int Cours_Ins_ID { get; set; }
    
        public virtual Cours_Cond Cours_Cond { get; set; }
        public virtual Inscription Inscription { get; set; }
    }
}
