//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscription()
        {
            this.Cours_Ins = new HashSet<Cours_Ins>();
            this.Medicament_Ins = new HashSet<Medicament_Ins>();
            this.Problemes_Ins = new HashSet<Problemes_Ins>();
            this.Revenu_Ins = new HashSet<Revenu_Ins>();
        }
    
        public int Ins_ID { get; set; }
        public System.DateTime Ins_DateDebut { get; set; }
        public Nullable<System.DateTime> Ins_DateFin { get; set; }
        public string Ins_Raison { get; set; }
        public string Ins_ContactUrgenceName { get; set; }
        public string Ins_ContactUrgenceTel { get; set; }
        public string Ins_ContactUrgenceLien { get; set; }
        public bool Ins_ADMTiers { get; set; }
        public bool Ins_PreuveResidence { get; set; }
        public Nullable<int> CoursCond_ID { get; set; }
        public int Provenance_ID { get; set; }
        public int Ref_ID { get; set; }
        public int Hebergement_ID { get; set; }
        public int Bnf_ID { get; set; }
        public int Chambre_ID { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual Chambre Chambre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours_Ins> Cours_Ins { get; set; }
        public virtual Provenance Provenance { get; set; }
        public virtual Source_Ref Source_Ref { get; set; }
        public virtual Type_Hebergment Type_Hebergment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicament_Ins> Medicament_Ins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problemes_Ins> Problemes_Ins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revenu_Ins> Revenu_Ins { get; set; }
    }
}
