//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problemes_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Problemes_Type()
        {
            this.Problemes_Ins = new HashSet<Problemes_Ins>();
        }
    
        public int Prob_ID { get; set; }
        public string Prob_Name { get; set; }
        public string Prob_Desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problemes_Ins> Problemes_Ins { get; set; }
    }
}
