//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problemes_Ins
    {
        public int ProbIns_ID { get; set; }
        public string ProbIns_MedecinName { get; set; }
        public string ProbIns_PsychiatreName { get; set; }
        public string ProbIns_MedTel { get; set; }
        public int Ins_ID { get; set; }
        public int Prob_ID { get; set; }
    
        public virtual Inscription Inscription { get; set; }
        public virtual Problemes_Type Problemes_Type { get; set; }
    }
}
