//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenu_Ins
    {
        public int RevenuIns_ID { get; set; }
        public decimal RevenuIns_Montant { get; set; }
        public int Ins_ID { get; set; }
        public int Revenu_ID { get; set; }
    
        public virtual Inscription Inscription { get; set; }
        public virtual Revenu_Type Revenu_Type { get; set; }
    }
}
