//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sante
    {
        public int Sante_Ins_ID { get; set; }
        public int Type_ProbSante_ID { get; set; }
        public string Sante_Desc { get; set; }
        public string Sante_Name { get; set; }
        public int Bnf_ID { get; set; }
    
        public virtual Beneficiaire Beneficiaire { get; set; }
        public virtual Type_ProbSante Type_ProbSante { get; set; }
    }
}
